# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

lzc-sdk-version: '0.1'
name: NextCloud
package: dev.libr.nextcloud
version: 0.0.7
description: >-
  Nextcloud is an open source file sync and sharing platform for private cloud
  storage, collaboration, and data privacy.
homepage: https://nextcloud.com/
author: Nextcloud contributors
application:
  subdomain: nextcloud
  background_task: false
  multi_instance: false
  routes:
    - /=http://nextcloud.dev.libr.nextcloud.lzcapp:80
  injects:
    - id: open-save-chooser
      on: browser
      when:
        - /*
      do:
        - src: file:///lzcapp/pkg/content/lazycat-injects/vendor/lzc-file-pickers.umd.js
        - src: file:///lzcapp/pkg/content/lazycat-injects/open-save-chooser.js
ext_config:
  enable_document_access: true
services:
  nextcloud:
    image: registry.lazycat.cloud/u30266047/library/nextcloud:5e363e4e9b2d2d53
    depends_on:
      - mysql
    user: root
    binds:
      - /lzcapp/var/nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_PASSWORD=LAZYCAT
      - MYSQL_HOST=mysql
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.${LAZYCAT_BOX_DOMAIN}
      - OVERWRITEPROTOCOL=https
      - APACHE_DISABLE_REWRITE_IP=1
    setup_script: |
      sh /lzcapp/pkg/content/backup/backup.sh
  mysql:
    image: registry.lazycat.cloud/u30266047/library/mysql:6761df2170dc166d
    binds:
      - /lzcapp/var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=LAZYCAT
      - MYSQL_DATABASE=nextcloud
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -pLAZYCAT
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
